version: "3.9"

services:
    #MySql
    db:
        image: mysql:8
        container_name: jnd_mysql
        volumes:
            - ./mysql/:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=jnddb
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=1234
        # restart: always
        networks:
            - web_network
    #Laravel App
    app:
        command:
            sh -c "mkdir mysql && if ! [ -f '.env' ]; then cp .env.example .env; fi &&
            chmod -R 777 storage &&
            if ! [ -d 'vendor' ]; then composer install --no-ansi --no-interaction --no-progress --optimize-autoloader --prefer-dist; fi &&
            if ! grep -Fq "APP_KEY=base64:" .env ; then php artisan key:generate; fi &&
            php artisan storage:link &&
            php artisan migrate && php artisan db:seed"
        build:
            args:
                user: tor
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        # image: laravel_for_work
        image: jnd-app
        container_name: jnd_app
        # restart: always
        volumes:
            - ./:/var/www/
        working_dir: /var/www/
        # ports:
        #     - "9000:5173"
        networks:
            - web_network
    #nginx service
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        depends_on:
            - app
        volumes:
            - ./:/var/www
            - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        ports:
            - "9000:80"
        restart: always
        networks:
            - web_network
    node:
        command: sh -c "npm install && npm run dev"
        container_name: node
        depends_on:
            - nginx
        hostname: node
        image: node:19-alpine
        ports:
            - 443:443
        volumes:
            - ./:/var/www
        working_dir: /var/www
        networks:
            - web_network
    phpmyadmin:
        image: phpmyadmin
        container_name: jnd_laravel_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8988:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - web_network
networks:
    web_network:
        name: laravel
        driver: bridge
